name: Blog build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog-config repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: recursive

      - name: Checkout blog content
        uses: actions/checkout@v6.0.2
        with:
          repository: StevenMaude/blog-content
          path: content
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install packages
        run: uv sync --locked

      - name: Build site
        run: |
          uv run make publish
