name: Blog build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog-config repository
        uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Checkout blog content
        uses: actions/checkout@v7.0.1
        with:
          repository: StevenMaude/blog-content
          path: content
          submodules: recursive

      - name: Build Docker image
        run: docker build --pull --tag blog-config:ci .
