name: Blog build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog-config repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout blog content
        uses: actions/checkout@v4
        with:
          repository: StevenMaude/blog-content
          path: content
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt

      - name: Build site
        run: |
          make publish
