name: Blog build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout blog-config repository
        uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Checkout blog content
        uses: actions/checkout@v7.0.1
        with:
          repository: StevenMaude/blog-content
          path: content
          submodules: recursive

      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install packages
        run: uv sync --locked

      - name: Build site
        run: |
          uv run make publish
